version: '3.5'

volumes:
  portal_dev_ssl:
    external: true

networks:
  default:
    external:
      name: macvlan111

services:
  frontend:
    container_name: ${STAND}_portal-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      org.label-schema.group: ${COMPOSE_PROJECT_NAME}
    restart: 'no'
    volumes:
      - portal_dev_ssl:/https:ro
    networks:
      default:
        aliases:
          - portal-frontend.dcs.infosec.ru
    ports:
      - '80:80'
